# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("counterparties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercounterpartyaccess",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_access",
                to="counterparties.counterparty",
            ),
        ),
        migrations.AddField(
            model_name="usercounterpartyaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counterparty_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="accounts_ac_user_id_9bf4ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["object_type", "object_id"], name="accounts_ac_object__031b8c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercounterpartyaccess",
            unique_together={("user", "counterparty")},
        ),
    ]
