# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counterparties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("initial", "Первоначальная загрузка"),
                            ("incremental", "Обновление (дельта)"),
                            ("on_demand", "Импорт по требованию"),
                        ],
                        max_length=20,
                        verbose_name="Режим импорта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("processing", "Обработка"),
                            ("validating", "Валидация"),
                            ("completed", "Завершён"),
                            ("completed_warnings", "Завершён с предупреждениями"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("xml", "XML"), ("excel", "Excel")],
                        max_length=10,
                        verbose_name="Формат файла",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to="imports/%Y/%m/", verbose_name="Загруженный файл"),
                ),
                ("total_records", models.IntegerField(default=0, verbose_name="Всего записей")),
                ("processed_records", models.IntegerField(default=0, verbose_name="Обработано")),
                ("created_records", models.IntegerField(default=0, verbose_name="Создано")),
                ("updated_records", models.IntegerField(default=0, verbose_name="Обновлено")),
                ("error_records", models.IntegerField(default=0, verbose_name="Ошибок")),
                (
                    "checksum",
                    models.CharField(blank=True, max_length=64, verbose_name="Контрольная сумма"),
                ),
                (
                    "duplicates_found",
                    models.IntegerField(default=0, verbose_name="Найдено дублей"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершение"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                        ],
                        max_length=10,
                        verbose_name="Уровень",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "row_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Номер строки"),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип объекта"),
                ),
                (
                    "object_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Данные объекта"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="data_import.importsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись лога импорта",
                "verbose_name_plural": "Логи импорта",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "new_counterparty_data",
                    models.JSONField(verbose_name="Данные нового контрагента"),
                ),
                (
                    "match_field",
                    models.CharField(
                        help_text="inn или name", max_length=50, verbose_name="Поле совпадения"
                    ),
                ),
                (
                    "match_confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="1.0 = точное совпадение ИНН, <1.0 = нечёткое совпадение имени",
                        verbose_name="Уверенность совпадения",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает решения"),
                            ("merge", "Объединить"),
                            ("keep_both", "Оставить оба"),
                            ("ignore", "Игнорировать"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Решение",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "existing_counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_existing",
                        to="counterparties.counterparty",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicates",
                        to="data_import.importsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат на дублирование",
                "verbose_name_plural": "Кандидаты на дублирование",
            },
        ),
    ]
