# Generated by Django 5.1.15 on 2026-04-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(default="", max_length=64, unique=True, verbose_name="Ключ"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название системы")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"read": true, "write": true, "sync_back": true}',
                        verbose_name="Разрешения",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее использование"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API-токен",
                "verbose_name_plural": "API-токены",
            },
        ),
        migrations.CreateModel(
            name="SyncSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("incoming", "Из 1С в платформу"),
                            ("outgoing", "Из платформы в 1С"),
                        ],
                        max_length=10,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="started",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200, verbose_name="Эндпоинт")),
                (
                    "records_received",
                    models.IntegerField(default=0, verbose_name="Получено записей"),
                ),
                ("records_created", models.IntegerField(default=0, verbose_name="Создано")),
                ("records_updated", models.IntegerField(default=0, verbose_name="Обновлено")),
                ("records_errors", models.IntegerField(default=0, verbose_name="Ошибок")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Детали")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.apitoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия синхронизации",
                "verbose_name_plural": "Сессии синхронизации",
                "ordering": ["-started_at"],
            },
        ),
    ]
