# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counterparties", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractConditionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Действует по")),
                (
                    "payment_term_type",
                    models.CharField(max_length=20, verbose_name="Тип условий оплаты"),
                ),
                ("payment_days", models.PositiveIntegerField(verbose_name="Срок оплаты (дней)")),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Лимит кредитования",
                    ),
                ),
                ("penalty_info", models.TextField(blank=True, verbose_name="Штрафные санкции")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counterparties.contract"
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counterparties.counterparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "История условий договора",
                "verbose_name_plural": "Регистр истории условий",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="DebtByTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("planned_payment_date", models.DateField(verbose_name="Плановая дата оплаты")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Текущая"),
                            ("overdue_30", "Просрочена до 30 дней"),
                            ("overdue_60", "Просрочена 30–60 дней"),
                            ("overdue_90", "Просрочена 60–90 дней"),
                            ("overdue_90_plus", "Просрочена свыше 90 дней"),
                            ("doubtful", "Сомнительная"),
                        ],
                        default="current",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма (руб.)"
                    ),
                ),
                (
                    "amount_currency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Сумма в валюте договора",
                    ),
                ),
                (
                    "overdue_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Сумма просрочки"
                    ),
                ),
                ("overdue_days", models.IntegerField(default=0, verbose_name="Дней просрочки")),
                (
                    "record_date",
                    models.DateField(auto_now_add=True, db_index=True, verbose_name="Дата записи"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_records",
                        to="counterparties.counterparty",
                    ),
                ),
                (
                    "responsible_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_records",
                        to="documents.goodsreceipt",
                        verbose_name="Документ-основание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись регистра задолженности",
                "verbose_name_plural": "Регистр расчётов по срокам",
                "indexes": [
                    models.Index(
                        fields=["status", "-record_date"], name="registers_d_status_edb52b_idx"
                    ),
                    models.Index(
                        fields=["counterparty", "-record_date"],
                        name="registers_d_counter_e9ac87_idx",
                    ),
                    models.Index(
                        fields=["planned_payment_date"], name="registers_d_planned_6ea7e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlannedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(db_index=True, verbose_name="Плановая дата платежа"),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата оплаты"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма планового платежа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидается"),
                            ("completed", "Исполнен"),
                            ("overdue", "Просрочен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Высокий"), ("medium", "Средний"), ("low", "Низкий")],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deviation_days",
                    models.IntegerField(default=0, verbose_name="Отклонение (дни)"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_payments",
                        to="counterparties.counterparty",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_payments",
                        to="documents.goodsreceipt",
                        verbose_name="Документ-основание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плановый платёж",
                "verbose_name_plural": "Регистр плановых платежей",
                "ordering": ["planned_date"],
                "indexes": [
                    models.Index(
                        fields=["planned_date", "status"], name="registers_p_planned_7a4260_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcurementVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("month", "Месяц"), ("quarter", "Квартал"), ("year", "Год")],
                        max_length=10,
                        verbose_name="Тип периода",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "procurement_kind",
                    models.CharField(
                        choices=[
                            ("raw", "Сырьё"),
                            ("material", "Материалы"),
                            ("service", "Услуги"),
                        ],
                        default="raw",
                        max_length=20,
                        verbose_name="Вид закупок",
                    ),
                ),
                (
                    "volume_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Объём закупок (руб.)"
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Доля в общем объёме (%)",
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Средняя цена закупки",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата расчёта"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_volumes",
                        to="counterparties.counterparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объём закупок",
                "verbose_name_plural": "Регистр объёмов закупок",
                "indexes": [
                    models.Index(
                        fields=["counterparty", "period_start"],
                        name="registers_p_counter_38f4b1_idx",
                    )
                ],
            },
        ),
    ]
