# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counterparties", "0001_initial"),
        ("directories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код в 1С"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата документа")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Сумма"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_due_date",
                    models.DateField(
                        help_text="Может определяться автоматически из условий договора",
                        verbose_name="Срок оплаты",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Оплаченная сумма"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Поступление товаров и услуг",
                "verbose_name_plural": "Поступления товаров и услуг",
                "ordering": ["-date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Количество"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Цена"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Сумма"),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=20, max_digits=5, verbose_name="Ставка НДС (%)"
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Сумма НДС"
                    ),
                ),
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directories.nomenclature",
                        verbose_name="Номенклатура",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.goodsreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка поступления",
                "verbose_name_plural": "Строки поступления",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код в 1С"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата документа")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Сумма"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Входящий"), ("outgoing", "Исходящий")],
                        default="incoming",
                        max_length=10,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок оплаты"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Счёт на оплату",
                "verbose_name_plural": "Счета на оплату",
                "ordering": ["-date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код в 1С"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата документа")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Сумма"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_purpose",
                    models.TextField(blank=True, verbose_name="Назначение платежа"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="documents.goodsreceipt",
                        verbose_name="Связанное поступление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёжное поручение",
                "verbose_name_plural": "Платёжные поручения",
                "ordering": ["-date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("60.01", "60.01 Расчёты с поставщиками"),
                            ("60.02", "60.02 Авансы выданные"),
                            ("60.21", "60.21 Расчёты в условных единицах"),
                            ("76", "76 Расчёты с разными дебиторами и кредиторами"),
                        ],
                        max_length=10,
                        verbose_name="Счёт",
                    ),
                ),
                ("balance_date", models.DateField(db_index=True, verbose_name="Дата остатка")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Дебет"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Кредит"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Сальдо"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.contract",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="counterparties.counterparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток по счёту",
                "verbose_name_plural": "Остатки по счетам",
                "ordering": ["-balance_date"],
                "indexes": [
                    models.Index(
                        fields=["account", "counterparty", "-balance_date"],
                        name="documents_a_account_ec2e91_idx",
                    )
                ],
            },
        ),
    ]
