# Generated by Django 5.1.15 on 2026-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="account",
            field=models.CharField(
                choices=[
                    ("60.01", "60.01 Расчёты с поставщиками"),
                    ("60.02", "60.02 Авансы выданные"),
                    ("60.21", "60.21 Расчёты в условных единицах"),
                    ("62", "62 Расчёты с покупателями"),
                    ("76", "76 Расчёты с разными дебиторами и кредиторами"),
                ],
                max_length=10,
                verbose_name="Счёт",
            ),
        ),
    ]
