# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True, verbose_name="Дата")),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Остаток на начало дня"
                    ),
                ),
                (
                    "total_inflow",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Входящие платежи"
                    ),
                ),
                (
                    "total_outflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Исходящие платежи",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Остаток на конец дня"
                    ),
                ),
                (
                    "is_cash_gap",
                    models.BooleanField(default=False, verbose_name="Кассовый разрыв"),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Прогнозный остаток",
                "verbose_name_plural": "Прогнозные остатки",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CashGapAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата кассового разрыва")),
                (
                    "deficit_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма дефицита"
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="Принято к сведению"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contributing_payments",
                    models.ManyToManyField(
                        blank=True,
                        to="registers.plannedpayment",
                        verbose_name="Платежи, вызывающие разрыв",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предупреждение о кассовом разрыве",
                "verbose_name_plural": "Предупреждения о кассовых разрывах",
                "ordering": ["date"],
            },
        ),
    ]
