# Generated by Django 6.0.5 on 2026-05-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
        ('documents', '0002_alter_accountbalance_account'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма к оплате')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('planned_date', models.DateField(help_text='Не должна быть в прошлом', verbose_name='Планируемая дата платежа')),
                ('purpose', models.TextField(help_text='Будет передано в 1С как назначение платежа', verbose_name='Назначение платежа')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На согласовании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('sent_to_1c', 'Отправлено в 1С'), ('posted_in_1c', 'Проведено в 1С'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, help_text='Заполняется бухгалтером при отклонении', verbose_name='Причина отклонения')),
                ('one_c_doc_key', models.CharField(blank=True, help_text='GUID созданного в 1С платёжного поручения', max_length=50, verbose_name='Ref_Key документа в 1С')),
                ('one_c_doc_number', models.CharField(blank=True, max_length=30, verbose_name='№ документа в 1С')),
                ('sent_to_1c_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в 1С')),
                ('one_c_error', models.TextField(blank=True, verbose_name='Ошибка при отправке в 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparties.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='counterparties.counterparty', verbose_name='Поставщик')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал (менеджер)')),
                ('related_receipt', models.ForeignKey(blank=True, help_text='Если заявка создана на оплату конкретной поставки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='documents.goodsreceipt', verbose_name='Поступление-основание')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Проверил (бухгалтер)')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=20, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.paymentrequest')),
            ],
            options={
                'verbose_name': 'Запись истории заявки',
                'verbose_name_plural': 'История заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_dfd796_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['counterparty', '-created_at'], name='payments_pa_counter_68babd_idx'),
        ),
    ]
