# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counterparties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода сверки")),
                ("period_end", models.DateField(verbose_name="Конец периода сверки")),
                (
                    "our_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Наше сальдо"
                    ),
                ),
                (
                    "their_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Сальдо контрагента",
                    ),
                ),
                ("is_matched", models.BooleanField(default=False, verbose_name="Данные совпали")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_acts",
                        to="counterparties.counterparty",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт сверки",
                "verbose_name_plural": "Акты сверки",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "document_ref",
                    models.CharField(max_length=200, verbose_name="Документ расхождения"),
                ),
                (
                    "our_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма по нашим данным"
                    ),
                ),
                (
                    "their_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Сумма по данным контрагента",
                    ),
                ),
                (
                    "discrepancy_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма расхождения"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("missing_doc", "Отсутствует документ"),
                            ("amount_mismatch", "Расхождение в сумме"),
                            ("date_mismatch", "Расхождение в дате"),
                            ("duplicate", "Дублирование"),
                            ("other", "Иное"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыто"),
                            ("in_progress", "В работе"),
                            ("resolved", "Закрыто"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "resolution_comment",
                    models.TextField(blank=True, verbose_name="Комментарий по урегулированию"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата закрытия"),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counterparties.counterparty",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reconciliation_act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="reconciliation.reconciliationact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расхождение",
                "verbose_name_plural": "Расхождения при сверке",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="reconciliat_status_6504e7_idx"
                    )
                ],
            },
        ),
    ]
