# Generated by Django 5.1.15 on 2026-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата расчёта")),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Общая сумма КЗ"
                    ),
                ),
                (
                    "overdue_debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Просроченная КЗ"
                    ),
                ),
                (
                    "overdue_ratio",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Доля просроченной КЗ (%)"
                    ),
                ),
                (
                    "turnover_days",
                    models.DecimalField(
                        decimal_places=1, max_digits=7, verbose_name="Оборачиваемость КЗ (дни)"
                    ),
                ),
                (
                    "payment_ratio",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Коэффициент погашения"
                    ),
                ),
                (
                    "avg_payment_days",
                    models.DecimalField(
                        decimal_places=1, max_digits=7, verbose_name="Средний срок оплаты (дни)"
                    ),
                ),
                (
                    "avg_deviation_days",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=7,
                        verbose_name="Среднее отклонение от договорных сроков (дни)",
                    ),
                ),
                (
                    "key_supplier_share",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Доля ключевых поставщиков (%)",
                    ),
                ),
                (
                    "forecast_cash_need_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Прогноз потребности (неделя)",
                    ),
                ),
                (
                    "forecast_cash_need_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Прогноз потребности (месяц)",
                    ),
                ),
                (
                    "cash_gap_probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Вероятность кассового разрыва (%)",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Аналитический снимок",
                "verbose_name_plural": "Аналитические снимки",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
    ]
