# Generated by Django 5.1.15 on 2026-04-14 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counterparties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("overdue_registry", "Реестр просроченной задолженности"),
                            ("payment_calendar", "Платёжный календарь"),
                            ("procurement_structure", "Структура закупок"),
                            ("debt_by_terms", "Задолженность по срокам"),
                            ("counterparty_card", "Карточка контрагента"),
                        ],
                        max_length=32,
                        verbose_name="Тип отчёта",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("excel", "Excel"), ("pdf", "PDF")],
                        max_length=8,
                        verbose_name="Формат",
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True, verbose_name="Дата с")),
                ("date_to", models.DateField(blank=True, null=True, verbose_name="Дата по")),
                ("file", models.FileField(upload_to="reports/%Y/%m/", verbose_name="Файл")),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Размер файла (байт)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сформировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный отчёт",
                "verbose_name_plural": "История отчётов",
                "ordering": ["-created_at"],
            },
        ),
    ]
