# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный идентификатор из учётной системы 1С",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Код в 1С",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=500, verbose_name="Наименование"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Полное наименование"
                    ),
                ),
                ("inn", models.CharField(db_index=True, max_length=12, verbose_name="ИНН")),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                ("legal_address", models.TextField(blank=True, verbose_name="Юридический адрес")),
                ("actual_address", models.TextField(blank=True, verbose_name="Фактический адрес")),
                ("phone", models.CharField(blank=True, max_length=100, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=300, verbose_name="Контактное лицо"),
                ),
                (
                    "is_key_supplier",
                    models.BooleanField(
                        default=False,
                        help_text="Поставщик, обеспечивающий 80% закупок",
                        verbose_name="Ключевой поставщик",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "responsible_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_counterparties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_1c",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Код в 1С"
                    ),
                ),
                ("number", models.CharField(max_length=100, verbose_name="Номер договора")),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Наименование"),
                ),
                ("date", models.DateField(verbose_name="Дата заключения")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("supply", "Поставка"),
                            ("service", "Оказание услуг"),
                            ("work", "Подряд"),
                            ("lease", "Аренда"),
                            ("other", "Прочее"),
                        ],
                        default="supply",
                        max_length=20,
                        verbose_name="Вид договора",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "Российский рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("CU", "Условные единицы"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "payment_term_type",
                    models.CharField(
                        choices=[
                            ("prepayment", "Предоплата"),
                            ("deferred", "Отсрочка платежа"),
                            ("on_delivery", "По факту поставки"),
                            ("mixed", "Смешанная"),
                        ],
                        default="deferred",
                        max_length=20,
                        verbose_name="Тип условий оплаты",
                    ),
                ),
                (
                    "payment_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Количество дней на оплату от даты документа",
                        verbose_name="Срок оплаты (дней)",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Лимит кредитования",
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ставка штрафных санкций (%)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="Действует с"),
                ),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Действует по")),
                ("is_active", models.BooleanField(default=True, verbose_name="Действующий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CounterpartyHistorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Дата снимка")),
                ("data", models.JSONField(verbose_name="Данные на дату")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_snapshots",
                        to="counterparties.counterparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок контрагента",
                "verbose_name_plural": "Снимки контрагентов",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(fields=["inn"], name="counterpart_inn_bcaee1_idx"),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(fields=["is_key_supplier"], name="counterpart_is_key__d94736_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="counterpartyhistorysnapshot",
            unique_together={("counterparty", "snapshot_date")},
        ),
    ]
