# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Наименование")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Код")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("raw", "Сырьё"),
                            ("material", "Материалы"),
                            ("service", "Услуги"),
                            ("goods", "Товары"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Единица измерения"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатура",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Наименование")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Код")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="directories.department",
                        verbose_name="Родительское подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ["name"],
            },
        ),
    ]
