# Generated by Django 5.1.15 on 2026-04-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overdue", "Просрочка платежа"),
                            ("cash_gap", "Кассовый разрыв"),
                            ("import_complete", "Импорт завершён"),
                            ("import_error", "Ошибка импорта"),
                            ("discrepancy", "Новое расхождение при сверке"),
                            ("system", "Системное уведомление"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("critical", "Критическое"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Важность",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL для перехода при клике",
                        max_length=500,
                        verbose_name="Ссылка",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "is_email_sent",
                    models.BooleanField(default=False, verbose_name="Email отправлен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Прочитано в"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    )
                ],
            },
        ),
    ]
